services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    env_file:
      - .env
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
  # minio:
  #   build:
  #     context: .
  #     dockerfile: minio/Dockerfile
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     - MINIO_ROOT_USER=root
  #     - MINIO_ROOT_PASSWORD=password
  #   volumes:
  #     - ./minio/data:/data
  # minio_config:
  #   image: minio/mc:RELEASE.2023-11-20T16-30-59Z
  #   volumes:
  #     - ./minio/mc:/mc
  #   entrypoint: /mc/config.sh
  #   env_file:
  #     - .env
  #   depends_on:
  #     - minio

